/* hardcoded data for SQL */

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10001, 'username', 'Learn JPA Framework', SYSDATE(), FALSE);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE)
VALUES(10002, 'username', 'Learn Spring', SYSDATE(), FALSE);